name: Build container images
on:
  push:
    branches:
      - '*'
#    tags:
#      - 'v*'
jobs:
  get_tags:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
        with:
          repository: Telmate/terraform-provider-proxmox

      - name: Get tags
        run: git tags
#  build:
#    strategy:
#      matrix:
#        container:
#          - terraform-provider-proxmox
#          - terraform-provider-proxmox-azrm
#          # This could be extended with other common backends (AWS, GCP, etc.)
#    runs-on: ubuntu-latest
#    steps:
#      - name: Checkout
#        uses: actions/checkout@v4.1.1
#
#      - name: Log in to Docker Hub
#        uses: redhat-actions/podman-login@v1.6
#        with:
#          username: "clincha"
#          password: ${{ secrets.DOCKER_PASSWORD }}
#          registry: docker.io
#
#      - name: ${{ matrix.container }} build and push
#        run: podman build . -f ./containers/$(DOCKERFILE) -t $(CONTAINER_REGISTRY)/$(CONTAINER_NAMESPACE)/$(CONTAINER_NAME):$(VERSION) --build-arg VERSION=$(VERSION)
