name: Build container images
on:
  push:
    branches:
      - '*'
#    tags:
#      - 'v*'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Log in to Docker Hub
        uses: redhat-actions/podman-login@v1.6
        with:
          username: "clincha"
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: build and push
        run: ./build_all_versions.sh
