name: Build container images
on:
  push:
    branches:
      - '*'
jobs:
  tags:
    runs-on: ubuntu-latest
    outputs:
      tags: ${{ steps.assign-tags.outputs.tags }}
    steps:
      - name: Checkout terraform-proxmox-provider
        uses: actions/checkout@v4.1.1
        with:
          repository: "Telmate/terraform-provider-proxmox"
          fetch-tags: true
          fetch-depth: 0

      - name: Install jq
        run: |
          sudo apt-get update
          sudo apt-get install -y jq

      - name: Assign tags to matrix variable
        id: assign-tags
        run: |
          git tag > tags.txt
          echo "tags=$(jq -Rcn '{"tags": [inputs]}' tags.txt)" >> $GITHUB_OUTPUT
  build:
    needs:
      - tags
    strategy:
      matrix: ${{ fromJson(needs.tags.outputs.tags) }}
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Install podman
        run: |
          sudo apt-get update
          sudo apt-get install -y podman

      - name: Log in to Docker Hub
        uses: redhat-actions/podman-login@v1.6
        with:
          username: "clincha"
          password: ${{ secrets.DOCKER_PASSWORD }}
          registry: docker.io

      - name: Checkout terraform-proxmox-provider
        uses: actions/checkout@v4.1.1
        with:
          repository: "Telmate/terraform-provider-proxmox"
          path: "terraform-provider-proxmox"
          ref: ${{ matrix.tags }}

      - name: build
        run: |
          podman build -t "docker.io/clincha/terraform-provider-proxmox:${{ matrix.tags }}" \
          --build-arg VERSION=${{ matrix.tags }} \
          --file containers/terraform-provider-proxmox.Dockerfile \
          --no-cache \
          ./terraform-provider-proxmox

      - name: push
        run: |
          podman push "docker.io/clincha/terraform-provider-proxmox:${{ matrix.tags }}"